//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1026
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WLCollect.WLBServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CollectByDateRange", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CollectByDateRange : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime DateField;
        
        private int CountsField;
        
        private int PackagesField;
        
        private decimal TotalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Counts {
            get {
                return this.CountsField;
            }
            set {
                if ((this.CountsField.Equals(value) != true)) {
                    this.CountsField = value;
                    this.RaisePropertyChanged("Counts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Packages {
            get {
                return this.PackagesField;
            }
            set {
                if ((this.PackagesField.Equals(value) != true)) {
                    this.PackagesField = value;
                    this.RaisePropertyChanged("Packages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public decimal Total {
            get {
                return this.TotalField;
            }
            set {
                if ((this.TotalField.Equals(value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WLB", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class WLB : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NodeField;
        
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        private System.DateTime CDTField;
        
        private WLCollect.WLBServiceReference.SKType SK_TypeField;
        
        private WLCollect.WLBServiceReference.YDType YD_TypeField;
        
        private WLCollect.WLBServiceReference.ZTType ZT_TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FH_CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FH_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FH_CityNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JH_CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JH_NameField;
        
        private System.DateTime CZ_RQField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CZ_BCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CZ_DZField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CZ_SJField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CZ_CPHField;
        
        private int CZ_LCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CZ_YXField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HW_MCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HW_LXField;
        
        private int HW_JSField;
        
        private decimal HW_BJField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FHR_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FHR_MobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FHR_RemarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JHR_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JHR_MobileField;
        
        private decimal JFZLField;
        
        private decimal JFTJField;
        
        private decimal TYFField;
        
        private decimal BZFField;
        
        private decimal BXFField;
        
        private decimal TotalField;
        
        private decimal MoneyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BXD_SNField;
        
        private bool FreezeField;
        
        private bool SyncedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SetsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Node {
            get {
                return this.NodeField;
            }
            set {
                if ((object.ReferenceEquals(this.NodeField, value) != true)) {
                    this.NodeField = value;
                    this.RaisePropertyChanged("Node");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string SN {
            get {
                return this.SNField;
            }
            set {
                if ((object.ReferenceEquals(this.SNField, value) != true)) {
                    this.SNField = value;
                    this.RaisePropertyChanged("SN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string UID {
            get {
                return this.UIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UIDField, value) != true)) {
                    this.UIDField = value;
                    this.RaisePropertyChanged("UID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime CDT {
            get {
                return this.CDTField;
            }
            set {
                if ((this.CDTField.Equals(value) != true)) {
                    this.CDTField = value;
                    this.RaisePropertyChanged("CDT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public WLCollect.WLBServiceReference.SKType SK_Type {
            get {
                return this.SK_TypeField;
            }
            set {
                if ((this.SK_TypeField.Equals(value) != true)) {
                    this.SK_TypeField = value;
                    this.RaisePropertyChanged("SK_Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public WLCollect.WLBServiceReference.YDType YD_Type {
            get {
                return this.YD_TypeField;
            }
            set {
                if ((this.YD_TypeField.Equals(value) != true)) {
                    this.YD_TypeField = value;
                    this.RaisePropertyChanged("YD_Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public WLCollect.WLBServiceReference.ZTType ZT_Type {
            get {
                return this.ZT_TypeField;
            }
            set {
                if ((this.ZT_TypeField.Equals(value) != true)) {
                    this.ZT_TypeField = value;
                    this.RaisePropertyChanged("ZT_Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string FH_Code {
            get {
                return this.FH_CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.FH_CodeField, value) != true)) {
                    this.FH_CodeField = value;
                    this.RaisePropertyChanged("FH_Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string FH_Name {
            get {
                return this.FH_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.FH_NameField, value) != true)) {
                    this.FH_NameField = value;
                    this.RaisePropertyChanged("FH_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string FH_CityName {
            get {
                return this.FH_CityNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FH_CityNameField, value) != true)) {
                    this.FH_CityNameField = value;
                    this.RaisePropertyChanged("FH_CityName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string JH_Code {
            get {
                return this.JH_CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.JH_CodeField, value) != true)) {
                    this.JH_CodeField = value;
                    this.RaisePropertyChanged("JH_Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string JH_Name {
            get {
                return this.JH_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.JH_NameField, value) != true)) {
                    this.JH_NameField = value;
                    this.RaisePropertyChanged("JH_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public System.DateTime CZ_RQ {
            get {
                return this.CZ_RQField;
            }
            set {
                if ((this.CZ_RQField.Equals(value) != true)) {
                    this.CZ_RQField = value;
                    this.RaisePropertyChanged("CZ_RQ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string CZ_BC {
            get {
                return this.CZ_BCField;
            }
            set {
                if ((object.ReferenceEquals(this.CZ_BCField, value) != true)) {
                    this.CZ_BCField = value;
                    this.RaisePropertyChanged("CZ_BC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string CZ_DZ {
            get {
                return this.CZ_DZField;
            }
            set {
                if ((object.ReferenceEquals(this.CZ_DZField, value) != true)) {
                    this.CZ_DZField = value;
                    this.RaisePropertyChanged("CZ_DZ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string CZ_SJ {
            get {
                return this.CZ_SJField;
            }
            set {
                if ((object.ReferenceEquals(this.CZ_SJField, value) != true)) {
                    this.CZ_SJField = value;
                    this.RaisePropertyChanged("CZ_SJ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string CZ_CPH {
            get {
                return this.CZ_CPHField;
            }
            set {
                if ((object.ReferenceEquals(this.CZ_CPHField, value) != true)) {
                    this.CZ_CPHField = value;
                    this.RaisePropertyChanged("CZ_CPH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=19)]
        public int CZ_LC {
            get {
                return this.CZ_LCField;
            }
            set {
                if ((this.CZ_LCField.Equals(value) != true)) {
                    this.CZ_LCField = value;
                    this.RaisePropertyChanged("CZ_LC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string CZ_YX {
            get {
                return this.CZ_YXField;
            }
            set {
                if ((object.ReferenceEquals(this.CZ_YXField, value) != true)) {
                    this.CZ_YXField = value;
                    this.RaisePropertyChanged("CZ_YX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string HW_MC {
            get {
                return this.HW_MCField;
            }
            set {
                if ((object.ReferenceEquals(this.HW_MCField, value) != true)) {
                    this.HW_MCField = value;
                    this.RaisePropertyChanged("HW_MC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string HW_LX {
            get {
                return this.HW_LXField;
            }
            set {
                if ((object.ReferenceEquals(this.HW_LXField, value) != true)) {
                    this.HW_LXField = value;
                    this.RaisePropertyChanged("HW_LX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=23)]
        public int HW_JS {
            get {
                return this.HW_JSField;
            }
            set {
                if ((this.HW_JSField.Equals(value) != true)) {
                    this.HW_JSField = value;
                    this.RaisePropertyChanged("HW_JS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=24)]
        public decimal HW_BJ {
            get {
                return this.HW_BJField;
            }
            set {
                if ((this.HW_BJField.Equals(value) != true)) {
                    this.HW_BJField = value;
                    this.RaisePropertyChanged("HW_BJ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=25)]
        public string FHR_Name {
            get {
                return this.FHR_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.FHR_NameField, value) != true)) {
                    this.FHR_NameField = value;
                    this.RaisePropertyChanged("FHR_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=26)]
        public string FHR_Mobile {
            get {
                return this.FHR_MobileField;
            }
            set {
                if ((object.ReferenceEquals(this.FHR_MobileField, value) != true)) {
                    this.FHR_MobileField = value;
                    this.RaisePropertyChanged("FHR_Mobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=27)]
        public string FHR_Remark {
            get {
                return this.FHR_RemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.FHR_RemarkField, value) != true)) {
                    this.FHR_RemarkField = value;
                    this.RaisePropertyChanged("FHR_Remark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=28)]
        public string JHR_Name {
            get {
                return this.JHR_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.JHR_NameField, value) != true)) {
                    this.JHR_NameField = value;
                    this.RaisePropertyChanged("JHR_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=29)]
        public string JHR_Mobile {
            get {
                return this.JHR_MobileField;
            }
            set {
                if ((object.ReferenceEquals(this.JHR_MobileField, value) != true)) {
                    this.JHR_MobileField = value;
                    this.RaisePropertyChanged("JHR_Mobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=30)]
        public decimal JFZL {
            get {
                return this.JFZLField;
            }
            set {
                if ((this.JFZLField.Equals(value) != true)) {
                    this.JFZLField = value;
                    this.RaisePropertyChanged("JFZL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=31)]
        public decimal JFTJ {
            get {
                return this.JFTJField;
            }
            set {
                if ((this.JFTJField.Equals(value) != true)) {
                    this.JFTJField = value;
                    this.RaisePropertyChanged("JFTJ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=32)]
        public decimal TYF {
            get {
                return this.TYFField;
            }
            set {
                if ((this.TYFField.Equals(value) != true)) {
                    this.TYFField = value;
                    this.RaisePropertyChanged("TYF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=33)]
        public decimal BZF {
            get {
                return this.BZFField;
            }
            set {
                if ((this.BZFField.Equals(value) != true)) {
                    this.BZFField = value;
                    this.RaisePropertyChanged("BZF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=34)]
        public decimal BXF {
            get {
                return this.BXFField;
            }
            set {
                if ((this.BXFField.Equals(value) != true)) {
                    this.BXFField = value;
                    this.RaisePropertyChanged("BXF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=35)]
        public decimal Total {
            get {
                return this.TotalField;
            }
            set {
                if ((this.TotalField.Equals(value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=36)]
        public decimal Money {
            get {
                return this.MoneyField;
            }
            set {
                if ((this.MoneyField.Equals(value) != true)) {
                    this.MoneyField = value;
                    this.RaisePropertyChanged("Money");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=37)]
        public string BXD_SN {
            get {
                return this.BXD_SNField;
            }
            set {
                if ((object.ReferenceEquals(this.BXD_SNField, value) != true)) {
                    this.BXD_SNField = value;
                    this.RaisePropertyChanged("BXD_SN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=38)]
        public bool Freeze {
            get {
                return this.FreezeField;
            }
            set {
                if ((this.FreezeField.Equals(value) != true)) {
                    this.FreezeField = value;
                    this.RaisePropertyChanged("Freeze");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=39)]
        public bool Synced {
            get {
                return this.SyncedField;
            }
            set {
                if ((this.SyncedField.Equals(value) != true)) {
                    this.SyncedField = value;
                    this.RaisePropertyChanged("Synced");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=40)]
        public string Sets {
            get {
                return this.SetsField;
            }
            set {
                if ((object.ReferenceEquals(this.SetsField, value) != true)) {
                    this.SetsField = value;
                    this.RaisePropertyChanged("Sets");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SKType", Namespace="http://tempuri.org/")]
    public enum SKType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        现金 = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        到付 = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        记账 = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="YDType", Namespace="http://tempuri.org/")]
    public enum YDType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        本地 = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        中心 = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        结账 = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ZTType", Namespace="http://tempuri.org/")]
    public enum ZTType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        接货 = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        装车 = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        卸车 = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        取货 = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        作废 = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WLBServiceReference.WLBServiceSoap")]
    public interface WLBServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 nodecode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMinDate", ReplyAction="*")]
        WLCollect.WLBServiceReference.GetMinDateResponse GetMinDate(WLCollect.WLBServiceReference.GetMinDateRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 nodecode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMaxDate", ReplyAction="*")]
        WLCollect.WLBServiceReference.GetMaxDateResponse GetMaxDate(WLCollect.WLBServiceReference.GetMaxDateRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 nodecode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCollectByDateRange", ReplyAction="*")]
        WLCollect.WLBServiceReference.GetCollectByDateRangeResponse GetCollectByDateRange(WLCollect.WLBServiceReference.GetCollectByDateRangeRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 nodecode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadByDate", ReplyAction="*")]
        WLCollect.WLBServiceReference.ReadByDateResponse ReadByDate(WLCollect.WLBServiceReference.ReadByDateRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMinDateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMinDate", Namespace="http://tempuri.org/", Order=0)]
        public WLCollect.WLBServiceReference.GetMinDateRequestBody Body;
        
        public GetMinDateRequest() {
        }
        
        public GetMinDateRequest(WLCollect.WLBServiceReference.GetMinDateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMinDateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nodecode;
        
        public GetMinDateRequestBody() {
        }
        
        public GetMinDateRequestBody(string nodecode) {
            this.nodecode = nodecode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMinDateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMinDateResponse", Namespace="http://tempuri.org/", Order=0)]
        public WLCollect.WLBServiceReference.GetMinDateResponseBody Body;
        
        public GetMinDateResponse() {
        }
        
        public GetMinDateResponse(WLCollect.WLBServiceReference.GetMinDateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMinDateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime GetMinDateResult;
        
        public GetMinDateResponseBody() {
        }
        
        public GetMinDateResponseBody(System.DateTime GetMinDateResult) {
            this.GetMinDateResult = GetMinDateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMaxDateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMaxDate", Namespace="http://tempuri.org/", Order=0)]
        public WLCollect.WLBServiceReference.GetMaxDateRequestBody Body;
        
        public GetMaxDateRequest() {
        }
        
        public GetMaxDateRequest(WLCollect.WLBServiceReference.GetMaxDateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMaxDateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nodecode;
        
        public GetMaxDateRequestBody() {
        }
        
        public GetMaxDateRequestBody(string nodecode) {
            this.nodecode = nodecode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMaxDateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMaxDateResponse", Namespace="http://tempuri.org/", Order=0)]
        public WLCollect.WLBServiceReference.GetMaxDateResponseBody Body;
        
        public GetMaxDateResponse() {
        }
        
        public GetMaxDateResponse(WLCollect.WLBServiceReference.GetMaxDateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMaxDateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime GetMaxDateResult;
        
        public GetMaxDateResponseBody() {
        }
        
        public GetMaxDateResponseBody(System.DateTime GetMaxDateResult) {
            this.GetMaxDateResult = GetMaxDateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCollectByDateRangeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCollectByDateRange", Namespace="http://tempuri.org/", Order=0)]
        public WLCollect.WLBServiceReference.GetCollectByDateRangeRequestBody Body;
        
        public GetCollectByDateRangeRequest() {
        }
        
        public GetCollectByDateRangeRequest(WLCollect.WLBServiceReference.GetCollectByDateRangeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCollectByDateRangeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nodecode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime minDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime maxDate;
        
        public GetCollectByDateRangeRequestBody() {
        }
        
        public GetCollectByDateRangeRequestBody(string nodecode, System.DateTime minDate, System.DateTime maxDate) {
            this.nodecode = nodecode;
            this.minDate = minDate;
            this.maxDate = maxDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCollectByDateRangeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCollectByDateRangeResponse", Namespace="http://tempuri.org/", Order=0)]
        public WLCollect.WLBServiceReference.GetCollectByDateRangeResponseBody Body;
        
        public GetCollectByDateRangeResponse() {
        }
        
        public GetCollectByDateRangeResponse(WLCollect.WLBServiceReference.GetCollectByDateRangeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCollectByDateRangeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WLCollect.WLBServiceReference.CollectByDateRange[] GetCollectByDateRangeResult;
        
        public GetCollectByDateRangeResponseBody() {
        }
        
        public GetCollectByDateRangeResponseBody(WLCollect.WLBServiceReference.CollectByDateRange[] GetCollectByDateRangeResult) {
            this.GetCollectByDateRangeResult = GetCollectByDateRangeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReadByDateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadByDate", Namespace="http://tempuri.org/", Order=0)]
        public WLCollect.WLBServiceReference.ReadByDateRequestBody Body;
        
        public ReadByDateRequest() {
        }
        
        public ReadByDateRequest(WLCollect.WLBServiceReference.ReadByDateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReadByDateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nodecode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime date;
        
        public ReadByDateRequestBody() {
        }
        
        public ReadByDateRequestBody(string nodecode, System.DateTime date) {
            this.nodecode = nodecode;
            this.date = date;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReadByDateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadByDateResponse", Namespace="http://tempuri.org/", Order=0)]
        public WLCollect.WLBServiceReference.ReadByDateResponseBody Body;
        
        public ReadByDateResponse() {
        }
        
        public ReadByDateResponse(WLCollect.WLBServiceReference.ReadByDateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReadByDateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WLCollect.WLBServiceReference.WLB[] ReadByDateResult;
        
        public ReadByDateResponseBody() {
        }
        
        public ReadByDateResponseBody(WLCollect.WLBServiceReference.WLB[] ReadByDateResult) {
            this.ReadByDateResult = ReadByDateResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WLBServiceSoapChannel : WLCollect.WLBServiceReference.WLBServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WLBServiceSoapClient : System.ServiceModel.ClientBase<WLCollect.WLBServiceReference.WLBServiceSoap>, WLCollect.WLBServiceReference.WLBServiceSoap {
        
        public WLBServiceSoapClient() {
        }
        
        public WLBServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WLBServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WLBServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WLBServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WLCollect.WLBServiceReference.GetMinDateResponse WLCollect.WLBServiceReference.WLBServiceSoap.GetMinDate(WLCollect.WLBServiceReference.GetMinDateRequest request) {
            return base.Channel.GetMinDate(request);
        }
        
        public System.DateTime GetMinDate(string nodecode) {
            WLCollect.WLBServiceReference.GetMinDateRequest inValue = new WLCollect.WLBServiceReference.GetMinDateRequest();
            inValue.Body = new WLCollect.WLBServiceReference.GetMinDateRequestBody();
            inValue.Body.nodecode = nodecode;
            WLCollect.WLBServiceReference.GetMinDateResponse retVal = ((WLCollect.WLBServiceReference.WLBServiceSoap)(this)).GetMinDate(inValue);
            return retVal.Body.GetMinDateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WLCollect.WLBServiceReference.GetMaxDateResponse WLCollect.WLBServiceReference.WLBServiceSoap.GetMaxDate(WLCollect.WLBServiceReference.GetMaxDateRequest request) {
            return base.Channel.GetMaxDate(request);
        }
        
        public System.DateTime GetMaxDate(string nodecode) {
            WLCollect.WLBServiceReference.GetMaxDateRequest inValue = new WLCollect.WLBServiceReference.GetMaxDateRequest();
            inValue.Body = new WLCollect.WLBServiceReference.GetMaxDateRequestBody();
            inValue.Body.nodecode = nodecode;
            WLCollect.WLBServiceReference.GetMaxDateResponse retVal = ((WLCollect.WLBServiceReference.WLBServiceSoap)(this)).GetMaxDate(inValue);
            return retVal.Body.GetMaxDateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WLCollect.WLBServiceReference.GetCollectByDateRangeResponse WLCollect.WLBServiceReference.WLBServiceSoap.GetCollectByDateRange(WLCollect.WLBServiceReference.GetCollectByDateRangeRequest request) {
            return base.Channel.GetCollectByDateRange(request);
        }
        
        public WLCollect.WLBServiceReference.CollectByDateRange[] GetCollectByDateRange(string nodecode, System.DateTime minDate, System.DateTime maxDate) {
            WLCollect.WLBServiceReference.GetCollectByDateRangeRequest inValue = new WLCollect.WLBServiceReference.GetCollectByDateRangeRequest();
            inValue.Body = new WLCollect.WLBServiceReference.GetCollectByDateRangeRequestBody();
            inValue.Body.nodecode = nodecode;
            inValue.Body.minDate = minDate;
            inValue.Body.maxDate = maxDate;
            WLCollect.WLBServiceReference.GetCollectByDateRangeResponse retVal = ((WLCollect.WLBServiceReference.WLBServiceSoap)(this)).GetCollectByDateRange(inValue);
            return retVal.Body.GetCollectByDateRangeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WLCollect.WLBServiceReference.ReadByDateResponse WLCollect.WLBServiceReference.WLBServiceSoap.ReadByDate(WLCollect.WLBServiceReference.ReadByDateRequest request) {
            return base.Channel.ReadByDate(request);
        }
        
        public WLCollect.WLBServiceReference.WLB[] ReadByDate(string nodecode, System.DateTime date) {
            WLCollect.WLBServiceReference.ReadByDateRequest inValue = new WLCollect.WLBServiceReference.ReadByDateRequest();
            inValue.Body = new WLCollect.WLBServiceReference.ReadByDateRequestBody();
            inValue.Body.nodecode = nodecode;
            inValue.Body.date = date;
            WLCollect.WLBServiceReference.ReadByDateResponse retVal = ((WLCollect.WLBServiceReference.WLBServiceSoap)(this)).ReadByDate(inValue);
            return retVal.Body.ReadByDateResult;
        }
    }
}
