//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1026
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WLCollect.DailySheetServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DailySheet", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DailySheet : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NodeCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NodeNameField;
        
        private int Counts1Field;
        
        private int Packages1Field;
        
        private decimal Total1Field;
        
        private int Counts2Field;
        
        private int Packages2Field;
        
        private decimal Total2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UIDField;
        
        private System.DateTime CDTField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NodeCode {
            get {
                return this.NodeCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.NodeCodeField, value) != true)) {
                    this.NodeCodeField = value;
                    this.RaisePropertyChanged("NodeCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NodeName {
            get {
                return this.NodeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.NodeNameField, value) != true)) {
                    this.NodeNameField = value;
                    this.RaisePropertyChanged("NodeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Counts1 {
            get {
                return this.Counts1Field;
            }
            set {
                if ((this.Counts1Field.Equals(value) != true)) {
                    this.Counts1Field = value;
                    this.RaisePropertyChanged("Counts1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int Packages1 {
            get {
                return this.Packages1Field;
            }
            set {
                if ((this.Packages1Field.Equals(value) != true)) {
                    this.Packages1Field = value;
                    this.RaisePropertyChanged("Packages1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public decimal Total1 {
            get {
                return this.Total1Field;
            }
            set {
                if ((this.Total1Field.Equals(value) != true)) {
                    this.Total1Field = value;
                    this.RaisePropertyChanged("Total1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int Counts2 {
            get {
                return this.Counts2Field;
            }
            set {
                if ((this.Counts2Field.Equals(value) != true)) {
                    this.Counts2Field = value;
                    this.RaisePropertyChanged("Counts2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int Packages2 {
            get {
                return this.Packages2Field;
            }
            set {
                if ((this.Packages2Field.Equals(value) != true)) {
                    this.Packages2Field = value;
                    this.RaisePropertyChanged("Packages2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public decimal Total2 {
            get {
                return this.Total2Field;
            }
            set {
                if ((this.Total2Field.Equals(value) != true)) {
                    this.Total2Field = value;
                    this.RaisePropertyChanged("Total2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string UID {
            get {
                return this.UIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UIDField, value) != true)) {
                    this.UIDField = value;
                    this.RaisePropertyChanged("UID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public System.DateTime CDT {
            get {
                return this.CDTField;
            }
            set {
                if ((this.CDTField.Equals(value) != true)) {
                    this.CDTField = value;
                    this.RaisePropertyChanged("CDT");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DailySheetServiceReference.DailySheetServiceSoap")]
    public interface DailySheetServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 nodecode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDailySheet", ReplyAction="*")]
        WLCollect.DailySheetServiceReference.GetDailySheetResponse GetDailySheet(WLCollect.DailySheetServiceReference.GetDailySheetRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDailySheetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDailySheet", Namespace="http://tempuri.org/", Order=0)]
        public WLCollect.DailySheetServiceReference.GetDailySheetRequestBody Body;
        
        public GetDailySheetRequest() {
        }
        
        public GetDailySheetRequest(WLCollect.DailySheetServiceReference.GetDailySheetRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDailySheetRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nodecode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime date;
        
        public GetDailySheetRequestBody() {
        }
        
        public GetDailySheetRequestBody(string nodecode, System.DateTime date) {
            this.nodecode = nodecode;
            this.date = date;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDailySheetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDailySheetResponse", Namespace="http://tempuri.org/", Order=0)]
        public WLCollect.DailySheetServiceReference.GetDailySheetResponseBody Body;
        
        public GetDailySheetResponse() {
        }
        
        public GetDailySheetResponse(WLCollect.DailySheetServiceReference.GetDailySheetResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDailySheetResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WLCollect.DailySheetServiceReference.DailySheet GetDailySheetResult;
        
        public GetDailySheetResponseBody() {
        }
        
        public GetDailySheetResponseBody(WLCollect.DailySheetServiceReference.DailySheet GetDailySheetResult) {
            this.GetDailySheetResult = GetDailySheetResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DailySheetServiceSoapChannel : WLCollect.DailySheetServiceReference.DailySheetServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DailySheetServiceSoapClient : System.ServiceModel.ClientBase<WLCollect.DailySheetServiceReference.DailySheetServiceSoap>, WLCollect.DailySheetServiceReference.DailySheetServiceSoap {
        
        public DailySheetServiceSoapClient() {
        }
        
        public DailySheetServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DailySheetServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DailySheetServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DailySheetServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WLCollect.DailySheetServiceReference.GetDailySheetResponse WLCollect.DailySheetServiceReference.DailySheetServiceSoap.GetDailySheet(WLCollect.DailySheetServiceReference.GetDailySheetRequest request) {
            return base.Channel.GetDailySheet(request);
        }
        
        public WLCollect.DailySheetServiceReference.DailySheet GetDailySheet(string nodecode, System.DateTime date) {
            WLCollect.DailySheetServiceReference.GetDailySheetRequest inValue = new WLCollect.DailySheetServiceReference.GetDailySheetRequest();
            inValue.Body = new WLCollect.DailySheetServiceReference.GetDailySheetRequestBody();
            inValue.Body.nodecode = nodecode;
            inValue.Body.date = date;
            WLCollect.DailySheetServiceReference.GetDailySheetResponse retVal = ((WLCollect.DailySheetServiceReference.DailySheetServiceSoap)(this)).GetDailySheet(inValue);
            return retVal.Body.GetDailySheetResult;
        }
    }
}
